### ISSUE TITLE
Angular 2 - (void 0) is not a function

### ISSUE THREAD

**Issue by Ionaru** [inorganik/countUp.js#133]
Using Angular-CLI 1.0.0-beta.21 (Angular 2.2.1)

I have imported the CountUpDirective in my app.module and added it to declarations, however I get this error:
```
Uncaught TypeError: (void 0) is not a function
```

Also the warning:
```
~/countup/dist/countUp.directive.js
System.register is not supported by webpack.
 @ ./src/app/app.module.ts 23:0-66
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```

Furthermore the documentation on how to use countUp.js with Angular2 seems out of date, the 'directives' attribute on a Component does no longer exist as of RC6

**Comment by inorganik** [comment]
This one is for @vigie, since he added Angular 2 support

**Comment by inorganik** [comment]
Pinging @vigie can you please look into this?

**Comment by vigie** [comment]
Hi @Ionaru I'm afraid I only tested this in an app where Systemjs was the loader and Angular was RC4. To fix the first issue, the `module` parameter in `tsconfig.json` should be changed to either `CommonJS` or `UMD`.

For the second issue, for now you can just list the directive in the `declarations` property of your app module, instead of the old `directives` property. I have tested this with Angular 2.2.4 and it is working (again, with SystemJS as the loader). Of course the proper fix is to create an `NgModule` and export the directive from there.

To summarize: a change should be prepared that does the following:

* Changes the `module` format in the `tsconfig.json`
* Updates the `package.json` `peerDependcies` to make the supported version of Angular expicit (^2.0.0)
* Creates an `NgModule` and exports the directive in the regular way
* Updates the README documentation to state that the above module should be imported into the AppModule, rather than explicitly declaring the contained directive.

I will certainly try to get to this change personally, but it might be a couple days so feel free to beat me to it...
