### ISSUE TITLE
How can I "destroy()" the plugin?

### ISSUE THREAD

**Issue by justrhysism** [inorganik/countUp.js#161]
I can't seem to find a way to "destroy" the plugin once I'm done with it. Does this have a different name, or is it not implemented?

**Comment by inorganik** [comment]
Interesting, I have never heard of a destroy method in javascript. It doesn't exist natively, since garbage collection is done automatically with js. As with any object in javascript though, you can simply delete it after it does what you need it to do. Here I call `delete` in the callback so it deletes after it finishes animating:

```js
var numAnim = new CountUp("SomeElementYouWantToAnimate", 24.02, 99.99);
numAnim.start(function() {
    delete numAnim;
});
```
These might free up a tiny bit of memory, but it will have **absolutely no performance benefit** in your app. 

It's completely unnecessary.
