### ISSUE TITLE
Constant repaints when the value has finished animating

### ISSUE THREAD

**Issue by xCausxn** [inorganik/countUp.js#164]
When using countUp in Angular there appear to be constant repaints when the value has seemed to have finished animating.

From looking at the countUp module for Angular 2 this is directly caused by:
https://github.com/inorganik/countUp.js/blob/master/countUp.module.ts#L115-L119

When removing the if statement for `endVal > 999` and only calling `this._countUp.start();` the issue is fixed.

I would create a PR to remove this but I am unsure why this if branch was added?

*note: this code is also present in the AngularJS version so the problem probably exists there as well.

**Comment by inorganik** [comment]
You'll notice up on line 107 of that file that there is another check for > 999. The reason is that it creates a smoother animation for large numbers. It subtracts 100 from the endVal on the initialization line, and when it starts down on the line you referenced, it uses the on-complete callback to call `update()` and finish the animation.

This technique is demonstrated here: http://inorganik.github.io/angular-scroll-spy/

In that case it's Angular 1.4.6 but it uses the same technique to smooth the animation for large numbers. The Angular modules still import the regular vanilla CountUp.js, and that code ensures requestAnimationFrame stops getting called after the end val is reached.

**Comment by UnwrittenFun** [comment]
The problem we ran into is that [here](https://github.com/inorganik/countUp.js/blob/master/countUp.module.ts#L116) the callback is set to call update [when the animation has finished](https://github.com/inorganik/countUp.js/blob/master/countUp.js#L172), however, update then [sets of the raf again](https://github.com/inorganik/countUp.js/blob/master/countUp.js#L214) causing essentially an infinite loop, and causing repaints every frame even when the number is stable.

**Comment by inorganik** [comment]
I see it now. I'm working on a fix. Thanks for bringing this to my attention.

**Comment by inorganik** [comment]
Ok, this is fixed in v1.8.5.
