### ISSUE TITLE
不能重复使用，不能更改数字样式  25，000.00只能这种。

### ISSUE THREAD

**Issue by y1310814423** [inorganik/countUp.js#198]
```
[ ] Bug
[
不能重复使用，我要是10几20个一起使用呢，我还的声明20个变量一个一个写？

 ] Feature request

CountUp.js version:

```

**Comment by inorganik** [comment]
I tried running your issue through google translate:
title: "Can't be reused, can't change number style 25,000.00 can only do this"
message: "Can not be reused, if I use a few 20 to 10 together, I also declare 20 variables one by one to write?"

I don't understand what your issue is. But you should have a separate instance of `countUp` for each animation.


我不明白你的问题是什么。但是，对于每个动画，您应该有一个单独的 `countUp` 实例。
