### ISSUE TITLE
Custom grouping function support

### ISSUE THREAD

**Issue by devWaleed** [inorganik/countUp.js#222]
@inorganik  Can you please add support for custom grouping function ? I want to group numbers in PKR currency format.

Like 1,050,200 should be 10,50,200 in PKR format.

Thanks

**Comment by inorganik** [comment]
For any custom grouping like this, you pass a custom formatting function, here's how:

```js
formatPKR(num) {
  ...
}

const countUp = new CountUp('targetId', 1050200, { formattingFn: formatPKR });
```

A formatting function takes a number and returns a string. The default one that comes with CountUp does the grouping and decimal formatting according to your options or the defaults, and numeral substitution, so if you pass one, it uses what you pass instead of the default.
