### ISSUE TITLE
如何在服务端渲染框架nuxt中使用，是否支持

### ISSUE THREAD

**Issue by hsinchumonkey** [inorganik/countUp.js#223]
```
[ ] Bug 如何在服务端渲染框架nuxt当中使用
[ ] Feature request

CountUp.js version:
1.0
```

**Comment by inorganik** [comment]
Google translated as "How to use in the server rendering framework nuxt, whether it is supported". I'm not sure. Going to close since this is a support request and not an issue. 

First try it out before filing an issue. As soon as the DOM is rendered, CountUp can run. So you just need to call `start()` inside a `window.onload` function or similar.
