### ISSUE TITLE
Script without export?

### ISSUE THREAD

**Issue by jenstornell** [inorganik/countUp.js#232]
```
[ ] Bug
[ x ] Feature request

CountUp.js version: 2.04
```

The script runs with export. Is it possible to run without it? The reason for it is that I combine all my scripts into one with Gulp.  Instead of 10 requests, I only get one which improves performance.

I've also added an question about it here:
https://stackoverflow.com/questions/60208128/gulp-concat-uglify-handling-es6-exported-libraries

**Comment by inorganik** [comment]
I googled it and found you can use a babel task to convert es6 modules to commonjs as part of your gulp pipe.

https://www.sitepoint.com/transpiling-es6-modules-to-amd-commonjs-using-babel-gulp/

Alternatively, you can use the commonjs version of this lib - in the [including countUp](https://github.com/inorganik/countUp.js#including-countup-) section of the README it lists different patch versions of countUp exported as different modules (because I was experimenting to find out which module was most compatible with the most projects).

I'll leave it to you to close this if one of these solutions works for you - thanks.

**Comment by jenstornell** [comment]
@inorganik Thanks! I think both your solutions looks good.

Now I use version 1.8.2 from here: https://www.jsdelivr.com/package/npm/countup. While it works fine for me now, I may outgrow it later, so your solutions will come in handy later on.

**Comment by inorganik** [comment]
Cool! But v1.8.2 is old. You can get commonjs module with v2.0.3 and get the latest/best code. Also the current docs won't work with 1.8, just fyi.

**Comment by jenstornell** [comment]
@inorganik Yes, I know but it worked for my current need. You can see the countup here https://vardagsfinans.se if you like. =)

But I'll upgrade as soon as I need to.

**Comment by inorganik** [comment]
Very nice, glad you got it working. v1.8 was distributed as a UMD module, if you are inclined, you can get v2 as a UMD module at v2.0.0.

I notice the height fluctuates on those divs with the counters, if you set a fixed width on `div.count` it will fix that.

**Comment by adeoy** [comment]
@jenstornell 
Hi, you only need to erase the last line in [`countUp.js/dist/countUp.js`](https://github.com/inorganik/countUp.js/blob/master/dist/countUp.js)
Example:
```javascript
// Remove this line!
// Line 248
export { CountUp };
```
