### ISSUE TITLE
Updated CDN Version on jsdeliver

### ISSUE THREAD

**Issue by lzinga** [inorganik/countUp.js#233]
```
[ ] Bug
[X] Feature request

CountUp.js version: 2.0.4

```

## Description
It would be great if the most updated version of this plugin was available on jsdeliver as it seems to be quite a few versions behind. Having a built version cdn that I can include easily into my non js framework process would be great to have.

**Comment by inorganik** [comment]
Have you looked at the demo in this repo? Check out `index.html`, it just includes the minified js for countUp, and demo.js which invokes countUp. There's no framework and no build system. The only caveat is you have to use a local server to avoid CORS issues because the scripts are included as modules. You can test the demo by running `npm run serve` which just serves index.html.

Also I looked at jsDelivr, it has the most recent version: https://www.jsdelivr.com/package/npm/countup.js
