### ISSUE TITLE
UMD module not added to global/window in browser

### ISSUE THREAD

**Issue by emattias** [inorganik/countUp.js#234]
The UMD module [if statement](https://github.com/inorganik/countUp.js/blob/2.0.0/dist/countUp.js#L13-L19) doesnt fall back to adding itself to the global variable (window in the browser).  

This is the fallback that is missing (from the umdjs repo example): https://github.com/umdjs/umd/blob/master/templates/returnExports.js#L26-L29

Also, how come the different versions arent added side by side in the latest version (with a `.umd.js` suffix for example) and instead have their own version?

**Comment by inorganik** [comment]
That UMD module code was generated by typescript about a year ago.

I hadn't considered shipping every module version...  the reason they are in past versions is because I was experimenting with different types of modules. I figured I would link to them as a convenience.

I don't think it's really necessary to ship every module version - the current version is an ES6 module, because it is the standard. All js frameworks and workflows should be headed toward ES6 modules or already use them. UMD and AMD modules existed to support modules before they became a standard. Older versions of CountUp.js packaged in these different module types should support legacy needs in the meantime.

If you _really_ need that if statement, I suggest you clone the project, update typescript, change the module setting in tsconfig, and generate the code you need. 

I hope that helps.

**Comment by emattias** [comment]
I whipped together a pr for this: https://github.com/inorganik/countUp.js/pull/235

**Comment by inorganik** [comment]
Hmm, did you read me reply?

**Comment by emattias** [comment]
Yeah I just wanted to offer the pr. You are of course free to close it if you dont want to UMD modules :)

**Comment by inorganik** [comment]
Is the whole point just to have `countUp` on window, without any imports?

**Comment by emattias** [comment]
Yeah to make it work by doing a regular old `<script />` tag, even in IE. If its on a cdn, like unpkg or jsDeliver for example, you dont even have to host it.

**Comment by inorganik** [comment]
This is now merged, UMD module is available in ./dist.
