### ISSUE TITLE
target class

### ISSUE THREAD

**Issue by marcobiedermann** [inorganik/countUp.js#64]
Is it possible to use a `target` class instead of an id?
I would like to call `var numAnim = new countUp();` only once.
My idea is to go over a loop of elements and get the options form `data-attribute`

**Comment by inorganik** [comment]
CountUp accepts either a var of a previously selected element or an id of an element. For your idea to work you'll need to refactor a bit. I think this would be a great learning opportunity for you. Fork this and try it out. Going to close this one because you're asking for this same thing in [this issue](https://github.com/inorganik/countUp.js/issues/60).
