### ISSUE TITLE
Count up an Element's Attribute value

### ISSUE THREAD

**Issue by AlexDar** [inorganik/countUp.js#83]
I'm not sure if this is possible with the current version. If it is how could I do it? If it isn't, would you consider adding the functionality? It would count up an attribute such as attrName in 
<code>
id="countMe" attrName="0"
</code>

Possible Usage: 

<code>
var element = new CountUp("countMe.attrName", 0, 80);
element.start();
</code>

or whatever is more programmer friendly.

To be exact I'm currently working with bootstrap progress bars http://getbootstrap.com/components/#progress and I'd like to animate both the number displayed to the user [working] and the width of the bar [not working] which happens to be defined via an attribute.

I also asked for a work around here http://stackoverflow.com/questions/32087028/parent-style-depends-on-childs-dynamic-value

**Comment by inorganik** [comment]
It's only a google search away Alex. I googled "javascript get attribute value" - 
```js
var target = document.getElementById('myTarget'),
    endVal = target.getAttribute('endVal'), // if you had an 'endVal' attribute on your target
    animation = new CountUp(target, 0, endVal).start();
```
http://jsfiddle.net/r5mdb61q/

**Comment by AlexDar** [comment]
Getting the attribute value is easy, changing the attribute value via countUp is what I can't seem to do!

As countUp runs on endVal, endVal should take on the values within the range and this should be reflected in the HTML. In your fiddle you are just using it as an upper bound, and it is a fixed value.

**Comment by inorganik** [comment]
There is no reason you should be blocked by using an attribute value- for the boostrap bar that is meant to be a "setter", so I think you should avoid that altogether and roll your own progress bar, It's really easy. You just absolutely position a div in another div, with the parent div having the following props: `overflow:hidden; position:relative` and the child div having `position:absolute; width:100%; left:100%; background:blue` Then you animate the `left` prop of the child div inside the `count` function in `CountUp` because it is firing every frame (because it's called by requestAnimationFrame()). In this way, the progress bar and the number animation are synced together.

**Comment by inorganik** [comment]
I think I'm understanding better what you are trying to do..... Just go inside the `count()` function and set the attribute of the progress bar there. Should be pretty darn close to:
```js
var percent = progress * 100
document.getElementById('progressBar').setAttribute('attrName', percent);
```
It was unclear to me what you were trying to do so sorry for all the back-n-forth.

**Comment by AlexDar** [comment]
Ahh, I didn't consider looking into the count function itself, I was too focused on finding an external way to do it. Yes this looks like it'd definitely work. 

I have another more makeshift solution which is to trigger a css transition of equal duration when start() is executed. So the number increases as does the bar width at the same time with no need for further calculations after the initial one.
