### ISSUE TITLE
CountUp preloader

### ISSUE THREAD

**Issue by satyasutar** [inorganik/countUp.js#92]
I want to start the counter as a preloader for a http request call in angular which returns me a number. And want to stop when the request is done and stop the counter at the number returned in response.
Basically an on-demand start and stop. Is there a way to do this?

**Comment by inorganik** [comment]
CountUp is designed for animating over a pre-determined duration, so you can't use it as a preloader, because the duration is unknown at the start. 

There is a nice angular lib you can try: http://chieffancypants.github.io/angular-loading-bar/

It's animating a bar from left to right, but you can hack it so it just animates that percentage width as a number.
